### ISSUE TITLE
Enabling SSL on HTTP not working

### ISSUE THREAD

**Issue by nin-o** [sherifabdlnaby/elastdocker#10]
Hello, thank you for the hard work on this project.

I uncommented the following lines in `elasticsearch/config/elasticsearch.yml`:

```
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: certs/elastic-certificates.p12
```
I noticed the following comment in the README file, but wasn't sure which specific action I need to take.

> Enabling SSL on HTTP layer will require all clients that connect to elasticsearch to configure SSL connection, this includes all current parts of the stack (e.g Logstash, Kibana, Curator, etc).

So I also updated `kibana/config/kibana.yml` to use `https` for `elasticsearch.hosts`.

When navigating to Kibana on my browser, it wasn't working. I checked the docker logs and it looked like Kibana was complaining about a self signed certificate. Note: before trying to setup SSL on HTTP, everything was working fine.

Some people online have suggested to convert `.p12` to `.pem` format. However I wanted to see if the author had any thoughts first.

I'm using Ubuntu. Thanks again!

**Comment by sherifabdlnaby** [comment]
When enabling SSL/TLS secured communication to Elasticsearch cluster then every other client that uses Elasticsearch needs to be configured accordingly to be able to communicate with it.

In Kibana for example (reference [Encrypting communications in Kibana](https://www.elastic.co/guide/en/kibana/current/configuring-tls.html))

You need to add to configure the following
`elasticsearch.ssl.certificate:` and `elasticsearch.ssl.key:`

and the same requirement appliest to logstash and any other tool that interacts with Elasticsearch (including language libraries).

As for `.p12` and `.pem` format, I choose `.p12` because it was simpler to generate and configure which is the goal of this project, to have stuff working and simple, you can then convert to using `.pem` on your own version of Elastdocker setup.
