### ISSUE TITLE
Question, newbie.

### ISSUE THREAD

**Issue by ronsalas** [sherifabdlnaby/elastdocker#11]
1. After having cloned the repository, and executing "make setup" I have the following error:

**sudo make setup**
make[1]: Entering directory `/home/****/elastdocker'
Building certs
Step 1/4 : ARG ELK_VERSION
ERROR: Service 'certs' failed to build: Please provide a source image with `from` prior to commit
make[1]: *** [certs] Error 1
make[1]: Leaving directory `/home/****/elastdocker'
make: *** [setup] Error 2

2. When I run the command "make keystore" I get the following error:

**sudo make keystore**
Building keystore
Step 1/4 : ARG ELK_VERSION
ERROR: Service 'keystore' failed to build: Please provide a source image with `from` prior to commit
make: *** [keystore] Error 1

**Comment by sherifabdlnaby** [comment]
@ronsalas Can you please specify Docker's version you're using?

**Comment by sherifabdlnaby** [comment]
This error occurs because older Docker versions couldn't have tags in the `FROM` directive and wouldn't allow Dockerfiles to start with anything but `FROM`; which is not the case with elastdocker that uses `ARG ELK_VERSION` to specify the stack version.

Please Update your Docker version and try again.
