### ISSUE TITLE
ELK Status

### ISSUE THREAD

**Issue by Bouzeghoub** [sherifabdlnaby/elastdocker#15]
Hello,
I have problem 

![image](https://user-images.githubusercontent.com/16193005/86460284-0349e900-bd20-11ea-98e3-b9344a199871.png)

Best regards.

**Comment by sherifabdlnaby** [comment]
This is not a problem, Elasticsearch default sharding and replication configuration expect at least 3 nodes, when you're running only one node the health is YELLOW. 
You need to either:
1. Spin up two extra nodes using `make nodes`. However, this is redundant for local development(And in Production if all nodes are on the same host).
2. Change Elasticsearch default index sharding and replication to 1 and 0 respectively so that Health is GREEN in a single node ES cluster.

**Comment by Bouzeghoub** [comment]
Thank you so much.
Please could you show us steps for deploy elk and tools and integration plugin elastalert to kibana.

**Comment by sherifabdlnaby** [comment]
You're welcome.
Adding ElastAlert plugin to kibana is already setup, you'll just need to uncomment some code, and tweak anything that is no longer compatible with `7.8.0`.
