### ISSUE TITLE
'Your connection is not private'

### ISSUE THREAD

**Issue by stianvale** [sherifabdlnaby/elastdocker#25]
Hi! 
Great repo and article on towardsdatascience! Thanks for that! 

I am getting the 'Your connection is not private' when trying to access https://localhost:5601 (kibana) in my web browser (NET::ERR_CERT_AUTHORITY_INVALID). 

Do you have any ideas on what might be missing in order to get the certificate validated? 

Best regards,
Stian

**Comment by sherifabdlnaby** [comment]
That's normal, we're using a "self-signed" certificates, so your browser will warn you about this because in an actual production website you'll need to sign your certificate with a Certificate Authority Service.

Anyway, I'll assume you're using Chrome, just click "Advanced Options" -> "Proceed To Website Anyway"
